@startuml
skinparam classAttributeIconSize 0
skinparam monochrome true
hide circle

class School {
  grades: Object
  constructor()
  roster(): Object
  add(student: String, grade: Number): undefined
  grade(grade: Number): Array<Number>
}
@enduml